### ISSUE TITLE
Report success while having FAIL cases on gophercloud

### ISSUE THREAD

**Issue by yongfengdu** [theopenlab/openlab-zuul-jobs#219]
The acceptance test has FAIL cases, but the CI result is SUCCESS, as reported here:
https://github.com/gophercloud/gophercloud/pull/1002#issuecomment-389381475

Check the test logs
http://logs.openlabtesting.org/logs/02/1002/fb9ac6f4e9f631e68938ea5b830cbac95d1bea75/check/gophercloud-acceptance-test/043ea6c/job-output.txt.gz

Looks like there are problems parsing this file after test
/home/zuul/workspace/test_results.xml

**Comment by kiwik** [comment]
This change cause the issue https://github.com/gophercloud/gophercloud/pull/996/files , should be fixed in script/acceptancetest of gophercloud project, add `set -e`

**Comment by liu-sheng** [comment]
@yongfengdu Hi, sorry for reply lately, just checked, seems it is because you have extracted all the "go test ..." statements into a script `script/acceptancetest`, in the job definition, the job running state is depends on the exit code of the playbook definition. if the `acceptancetest` don't exit with non-zero code when some tests running failed, the job will report success. maybe you can help to add a `set -e` in the header of the script to avoid that issue.
