### ISSUE TITLE
Add ARM nodesets

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab-zuul-jobs#446]
ubuntu-xenial-vxh-arm64
ubuntu-bionic-vxh-arm64
centos-7-vxh-arm64

**Comment by liu-sheng** [comment]
Hi Melvin, as we have reached an agreement, we should open all these issues in `https://github.com/theopenlab/openlab/issues`

**Comment by mrhillsman** [comment]
Having the requirement to fill out an issue at theopenlab/openlab for theopenlab/openlab-zuul-jobs introduces unnecessary complexity and bad ux/workflow for simple updates to jobs that live in this repo

**Comment by kiwik** [comment]
Hi, @mrhillsman our document website have desribed where we should report bug cleanly https://docs.openlabtesting.org/publications/contributors/development-guide#working-on-bug . We hope to use one place `theopenlab/openlab/issues` to trace all of related things, because we always fix one issue across sereval community projects.

**Comment by mrhillsman** [comment]
@kiwik yes I understand, but this is not a bug. Also, we should always be willing to review our ux/workflow for efficiency and adjust when appropriate. Maybe we should have an issue template for a feature request(s). However, we still need to inspect our ux/workflow regularly for efficiency opportunities.

**Comment by kiwik** [comment]
@mrhillsman Agree, I think we should add an issue template and document to introduce how to add features for OpenLab too, let me add a task into OpenLab TODO list.

**Comment by kiwik** [comment]
@mrhillsman trace the target here https://github.com/theopenlab/openlab/issues/203
